### ISSUE TITLE
Error updating miniPurple

### ISSUE THREAD

**Issue by johnsturgeon** [FlyingDiver/Indigo-miniPurple#1]
I'm sometimes getting the following error when updating my Purple Air device
```
   miniPurple Error                Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 51, in runConcurrentThread
  File "plugin.py", line 89, in getData
KeyError: 'results'

   miniPurple Error                plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
```

**Comment by FlyingDiver** [comment]
How often?

**Comment by johnsturgeon** [comment]
Just once... It did update later, so it might have just been a glitch w/PurpleAir

**Comment by FlyingDiver** [comment]
Probably was.  I'll add some code to trap that error so it doesn't crash the plugin.

**Comment by FlyingDiver** [comment]
Fixed in next release.
